In [3]:
# Import libraries required for data manipulation and cleaning
import pandas as pd
import numpy as np
import re

# Display all columns while exploring the dataset
pd.set_option("display.max_columns", None)

# Increase column width for better readability
pd.set_option("display.max_colwidth", 100)

In [4]:
# Read the CSV file into a Pandas DataFrame
df = pd.read_csv("Combined_dataset.csv")

# Display the number of rows and columns
print(f"Dataset loaded successfully.")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Dataset loaded successfully.
Rows: 1000
Columns: 24

In [5]:
# Display the first five records
display(df.head())

# Display the last five records
display(df.tail())

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/8376765/2019/2/14/c93b7d05-6311-497e-ad00-7395c266a97...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Navy Blue solid backpackNon-Padded haul loop1 main compartment with flap and but...","[{""name"":""Accessories"",""url"":""https://www.myntra.com/accessories""},{""name"":""Women"",""url"":""https:...","[{""specification_name"":""Add-Ons"",""specification_value"":""NA""},{""specification_name"":""Back"",""speci...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":4,""5_stars"":6}",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi Credit & Debit Cards "",""offer_value"":"" Min Spend ₹3...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/9136281/2021/1/5/76e86881-810a-4c7f-9860-4fc07a93571a...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Navy Blue backpackNon-Padded haul loop1 main compartment with zip closurePadded ...","[{""name"":""Accessories"",""url"":""https://www.myntra.com/accessories""},{""name"":""Unisex"",""url"":""https...","[{""specification_name"":""Add-Ons"",""specification_value"":""NA""},{""specification_name"":""Back"",""speci...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":8,""5_stars"":50}",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi Credit & Debit Cards "",""offer_value"":"" Min Spend ₹3...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/17633752/2022/12/2/798da268-99f2-43c5-bc75-676b69ade7...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Pink solid backpacks Non-padded sternum shoulder straps, has 1 main compartment...","[{""name"":""Accessories"",""url"":""https://www.myntra.com/accessories""},{""name"":""Women"",""url"":""https:...","[{""specification_name"":""Add-Ons"",""specification_value"":""NA""},{""specification_name"":""Back"",""speci...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars"":55,""5_stars"":147}",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/2022/8/2/393c1588-d2b2-4861-badf-afccccfd8b47_1763...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi Credit & Debit Cards "",""offer_value"":"" Min Spend ₹3...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/1376949/2022/12/1/756cb321-b3b8-4246-b3c7-317980b06b0...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Navy and grey printed backpackOne haul loop, two padded and adjustable shoulder ...","[{""name"":""Accessories"",""url"":""https://www.myntra.com/accessories""},{""name"":""Unisex"",""url"":""https...","[{""specification_name"":""Compartment Closure"",""specification_value"":""Drawstring""},{""specification...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_stars"":282,""5_stars"":647}",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/2022/6/22/6a7c815d-9e1d-4af7-bcf5-4549a9a6abf7_137...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi Credit & Debit Cards "",""offer_value"":"" Min Spend ₹3...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/productimage/2021/3/23/ce9de137-9aae-4010-b713-071256...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Blue solid bath robe, has a shawl collar with an open front, three-quarter sleev...","[{""name"":""Men"",""url"":""https://www.myntra.com/men-home""},{""name"":""Bath Robe"",""url"":""https://www.m...","[{""specification_name"":""Body or Garment Size"",""specification_value"":""Garment Measurements in""},{...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":4,""5_stars"":8}",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Front Length""},{""size"":""M"",""value"":""41.0in"",""value_n...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusInd Bank Debit Cards "",""offer_value"":"" Min Spend ₹2...",bath-robe

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue Watch-KW039,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/13698258/2021/2/20/370fa6db-cc8d-434e-a127-cdcb4c8cf0...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Features:Nothing about the Forte is subtle, it's bold from the get go and you'll...","[{""name"":""Accessories"",""url"":""https://www.myntra.com/accessories""},{""name"":""Men"",""url"":""https://...","[{""specification_name"":""Add-Ons"",""specification_value"":""NA""},{""specification_name"":""Collection N...","{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":1,""5_stars"":5}",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi Credit & Debit Cards "",""offer_value"":"" Min Spend ₹3...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Analogue Watch GW0359L2,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/16896006/2022/4/5/99b34fa9-b59a-43da-a759-f85da43a8f7...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Pack Contains: single watchDisplay: analogueMovement: quartzPower Source: batter...","[{""name"":""Accessories"",""url"":""https://www.myntra.com/accessories""},{""name"":""Women"",""url"":""https:...","[{""specification_name"":""Add-Ons"",""specification_value"":""NA""},{""specification_name"":""Case Thickne...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":1,""5_stars"":21}",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntassets.com/assets/videos/2022/7/19/6058050f-0336-4171-...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi Credit & Debit Cards "",""offer_value"":"" Min Spend ₹3...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch FA2052-55,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/1708108/2022/1/3/0f634e7d-14ec-4ceb-845a-29ffbec56b42...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Case style: Analogue watch, has a circular case and a stainless steel back Dial ...","[{""name"":""Accessories"",""url"":""https://www.myntra.com/accessories""},{""name"":""Women"",""url"":""https:...","[{""specification_name"":""Dial Material"",""specification_value"":""Stainless Steel""},{""specification_...","{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":0,""5_stars"":2}",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi Credit & Debit Cards "",""offer_value"":"" Min Spend ₹3...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel Straps Analogue Watch 3247NM03,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/19280114/2023/6/26/6d66293c-31f1-4e64-a273-efa882d24f...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Pack Contains: single watch Display: analogue Movement: quartz Power Source: ...","[{""name"":""Accessories"",""url"":""https://www.myntra.com/accessories""},{""name"":""Men"",""url"":""https://...","[{""specification_name"":""Add-Ons"",""specification_value"":""NA""},{""specification_name"":""Dial Colour""...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":2,""5_stars"":12}",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu█████████████████████del█████████████████████,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only on first purchase)"",""best_price"":""2236"",""coupon_co...","[{""offer_name"":""10% Instant Discount on IndusInd Bank Debit Cards "",""offer_value"":"" Min Spend ₹2...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/18601682/2023/5/20/5edd738f-b349-436b-8250-f67e0e1e3a...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 7 days returns and exchanges""]","{""description"":""Set content: One yoga matColour: PurpleMaterial: EVAShape: RectangularPattern: T...","[{""name"":""Unisex"",""url"":""https://www.myntra.com/unisex-home""},{""name"":""Yoga Mats"",""url"":""https:/...","[{""specification_name"":""Mat Thickness"",""specification_value"":""4 mm""},{""specification_name"":""Mate...","{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars"":26,""5_stars"":81}",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi Credit & Debit Cards "",""offer_value"":"" Min Spend ₹3...",yoga-mats

In [6]:
# View the dimensions of the dataset
print("Dataset Shape:", df.shape)

# Display all column names
print("\nColumn Names:")
print(df.columns.tolist())

Dataset Shape: (1000, 24)

Column Names:
['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [7]:
# Display column names, data types, and non-null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

In [8]:
# Generate summary statistics for numerical and categorical columns
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
product_id,1000.0,NaN,NaN,NaN,17134372.582,3813765.757473,586846.0,15115009.5,18208901.0,19027372.0,22747068.0
title,1000,454,Roadster,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_description,1000,989,Women Pink Solid Top,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rating,1000.0,NaN,NaN,NaN,3.6215,1.3744,0.0,3.7,4.1,4.3,5.0
ratings_count,1000.0,NaN,NaN,NaN,76.691,241.114263,0.0,7.0,17.0,58.0,4441.0
initial_price,1000.0,NaN,NaN,NaN,2723.241,2408.69736,249.0,1399.0,1999.0,3299.0,22199.0
discount,879.0,NaN,NaN,NaN,53.503982,18.029201,1.0,44.0,56.0,66.0,88.0
final_price,1000,466,"""₹999.00""",25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
currency,1000,1,INR,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
images,1000,1000,http://assets.myntassets.com/assets/images/18601682/2023/5/20/5edd738f-b349-436b-8250-f67e0e1e3a...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
delivery_options,1000,16,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...",650,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_details,1000,998,"{""description"":""Black and White printed knitted fit and flare dress, has a round neck, sleeveles...",2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
breadcrumbs,1000,658,"[{""name"":""Clothing"",""url"":""https://www.myntra.com/clothing""},{""name"":""Men"",""url"":""https://www.my...",16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_specifications,1000,967,"[{""specification_name"":""Blouse"",""specification_value"":""Blouse Piece""},{""specification_name"":""Blo...",4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
amount_of_stars,1000,808,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":0,""5_stars"":0}",114,NaN,NaN,NaN,NaN,NaN,NaN,NaN
what_customers_said,427,302,"[{""percentage"":""100"",""value_name"":""Fit, Just Right""},{""percentage"":""100"",""value_name"":""Length, J...",27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_name,699,301,Sup███om ███,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sizes,1000,672,"[{""size"":""Onesize""}]",135,NaN,NaN,NaN,NaN,NaN,NaN,NaN
videos,219,219,"[""rw-8376765_cae700""]",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_information,699,298,Plo███o- ███ 1s█████████Sui█████████████████████al ██████████████████████████████████████████,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
variations,438,22,[{}],126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
best_offer,1000,468,{},306,NaN,NaN,NaN,NaN,NaN,NaN,NaN
more_offers,1000,159,"[{""offer_name"":""10% Instant Discount on IndusInd Bank Debit Cards "",""offer_value"":"" Min Spend ₹2...",265,NaN,NaN,NaN,NaN,NaN,NaN,NaN
category,1000,97,tops,122,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Calculate missing values and their percentage
missing_values = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum() / len(df)) * 100
})

# Display only columns with missing values
missing_values = missing_values[missing_values["Missing Values"] > 0]

# Sort columns by highest percentage of missing values
missing_values = missing_values.sort_values(
    by="Percentage",
    ascending=False
)

display(missing_values)

                     Missing Values  Percentage
videos                          781        78.1
what_customers_said             573        57.3
variations                      562        56.2
seller_name                     301        30.1
seller_information              301        30.1
discount                        121        12.1

In [10]:
# Separate columns based on data type
text_columns = df.select_dtypes(include="object").columns
numeric_columns = df.select_dtypes(include=["int64", "float64"]).columns

# Replace missing text values with a placeholder
df[text_columns] = df[text_columns].fillna("Not Available")

# Replace missing numeric values with zero
df[numeric_columns] = df[numeric_columns].fillna(0)

# Verify that all missing values have been handled
print("Remaining missing values:", df.isnull().sum().sum())

Remaining missing values: 0

In [11]:
# Count duplicate rows before removal
duplicate_count = df.duplicated().sum()

print("Duplicate rows before removal:", duplicate_count)

# Remove duplicate records
df = df.drop_duplicates()

print("Dataset shape after removing duplicates:", df.shape)

Duplicate rows before removal: 0
Dataset shape after removing duplicates: (1000, 24)

In [12]:
# Select products with ratings greater than or equal to 4
high_rated_products = df[df["rating"] >= 4.0]

display(high_rated_products.head())

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/9136281/2021/1/5/76e86881-810a-4c7f-9860-4fc07a93571a...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Navy Blue backpackNon-Padded haul loop1 main compartment with zip closurePadded ...","[{""name"":""Accessories"",""url"":""https://www.myntra.com/accessories""},{""name"":""Unisex"",""url"":""https...","[{""specification_name"":""Add-Ons"",""specification_value"":""NA""},{""specification_name"":""Back"",""speci...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":8,""5_stars"":50}",Not Available,Not Available,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi Credit & Debit Cards "",""offer_value"":"" Min Spend ₹3...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/17633752/2022/12/2/798da268-99f2-43c5-bc75-676b69ade7...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Pink solid backpacks Non-padded sternum shoulder straps, has 1 main compartment...","[{""name"":""Accessories"",""url"":""https://www.myntra.com/accessories""},{""name"":""Women"",""url"":""https:...","[{""specification_name"":""Add-Ons"",""specification_value"":""NA""},{""specification_name"":""Back"",""speci...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars"":55,""5_stars"":147}",Not Available,Not Available,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/2022/8/2/393c1588-d2b2-4861-badf-afccccfd8b47_1763...",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi Credit & Debit Cards "",""offer_value"":"" Min Spend ₹3...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/1376949/2022/12/1/756cb321-b3b8-4246-b3c7-317980b06b0...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Navy and grey printed backpackOne haul loop, two padded and adjustable shoulder ...","[{""name"":""Accessories"",""url"":""https://www.myntra.com/accessories""},{""name"":""Unisex"",""url"":""https...","[{""specification_name"":""Compartment Closure"",""specification_value"":""Drawstring""},{""specification...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_stars"":282,""5_stars"":647}",Not Available,Not Available,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/2022/6/22/6a7c815d-9e1d-4af7-bcf5-4549a9a6abf7_137...",Not Available,Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi Credit & Debit Cards "",""offer_value"":"" Min Spend ₹3...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/productimage/2021/3/23/ce9de137-9aae-4010-b713-071256...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Blue solid bath robe, has a shawl collar with an open front, three-quarter sleev...","[{""name"":""Men"",""url"":""https://www.myntra.com/men-home""},{""name"":""Bath Robe"",""url"":""https://www.m...","[{""specification_name"":""Body or Garment Size"",""specification_value"":""Garment Measurements in""},{...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":4,""5_stars"":8}",Not Available,Not Available,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Front Length""},{""size"":""M"",""value"":""41.0in"",""value_n...",Not Available,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusInd Bank Debit Cards "",""offer_value"":"" Min Spend ₹2...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,0.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/17198778/2022/2/17/e3712bfd-2755-4038-8068-94b0594ee2...,"[""100% Original Products"",""Pay on delivery might be available"",""Easy 14 days returns and exchang...","{""description"":""Soap dispenser in glazed stoneware with a plastic pump."",""material_and_care"":""10...","[{""name"":""Unisex"",""url"":""https://www.myntra.com/unisex-home""},{""name"":""Bathroom Accessories"",""ur...","[{""specification_name"":""Finish"",""specification_value"":""Matte""},{""specification_name"":""Material"",...","{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":5,""5_stars"":33}",Not Available,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",Not Available,Pra███yat███fra█████████PVT█████████████████████-Sq█████████████████████████████████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only on first purchase)"",""best_price"":""1026"",""coupon_co...","[{""offer_name"":""10% Instant Discount on IndusInd Bank Debit Cards "",""offer_value"":"" Min Spend ₹2...",bathroom-accessories

In [13]:
# Create a subset containing relevant columns
selected_columns = df[
    ["title", "category", "final_price", "rating"]
]

display(selected_columns.head())

            title   category  final_price  rating
0     Lino Perros  backpacks  "₹3,995.00"     3.8
1  Tommy Hilfiger  backpacks  "₹2,899.00"     4.5
2           Lavie  backpacks  "₹2,999.00"     4.4
3          F Gear  backpacks  "₹1,675.00"     4.4
4       MYTRIDENT  bath-robe  "₹2,899.00"     4.7

In [15]:
#Convert Price to Numeric Format

# Function to remove currency symbols and commas from price values
def clean_price(price):

    # Return 0 for missing values
    if pd.isna(price):
        return 0.0

    # Keep only digits and decimal points
    cleaned = re.sub(r"[^0-9.]", "", str(price))

    return float(cleaned) if cleaned else 0.0


# Create a numeric version of the price column
df["final_price_numeric"] = df["final_price"].apply(clean_price)

In [16]:
# The dataset does not contain a quantity column.
# ratings_count is used as a proxy variable.

df["total_amount"] = (
    df["final_price_numeric"] * df["ratings_count"]
)

display(
    df[
        [
            "final_price",
            "final_price_numeric",
            "ratings_count",
            "total_amount"
        ]
    ].head()
)

   final_price  final_price_numeric  ratings_count  total_amount
0  "₹3,995.00"               3995.0             15       59925.0
1  "₹2,899.00"               2899.0             67      194233.0
2  "₹2,999.00"               2999.0            226      677774.0
3  "₹1,675.00"               1675.0           1052     1762100.0
4  "₹2,899.00"               2899.0             12       34788.0

In [17]:
# Define output file name
output_file = "Combined_dataset_cleaned.csv"

# Save the cleaned dataset without row indices
df.to_csv(output_file, index=False)

print(f"Cleaned dataset saved as '{output_file}'")

Cleaned dataset saved as 'Combined_dataset_cleaned.csv'

In [18]:
## Summary

# - Loaded the dataset into a Pandas DataFrame.
# - Explored the dataset using head(), tail(), shape, info(), and describe().
# - Identified and handled missing values.
# - Removed duplicate records.
# - Performed row filtering and column selection.
# - Converted the final_price column to numeric format.
# - Since the dataset did not contain a quantity column, ratings_count was used as a proxy variable.
# - Created the derived column total_amount.
# - Saved the cleaned dataset as Combined_dataset_cleaned.csv.